import { DataStructure, Algorithm, Challenge } from "./types";

export const dataStructures: DataStructure[] = [
  {
    slug: "array",
    name: "Array",
    category: "Linear",
    difficulty: "Beginner",
    description:
      "An array is a collection of elements stored at contiguous memory locations. Each element can be accessed directly using its index number. Think of it like a row of boxes, each with a number on it — you can immediately go to any box if you know its number.",
    shortDescription: "A collection of elements stored in contiguous memory locations, accessible by index.",
    operations: ["Access", "Search", "Insert", "Delete"],
    timeComplexity: { access: "O(1)", search: "O(n)", insert: "O(n)", delete: "O(n)" },
    advantages: ["Fast access by index", "Memory efficient", "Cache friendly"],
    disadvantages: ["Fixed size (in static arrays)", "Costly insertions/deletions", "Wasted space if not full"],
    useCases: ["Storing lists of data", "Lookup tables", "Buffering", "Matrices"],
  },
  {
    slug: "linked-list",
    name: "Linked List",
    category: "Linear",
    difficulty: "Beginner",
    description:
      "A linked list is a sequence of elements where each element (node) points to the next one. Unlike arrays, elements are not stored next to each other in memory. It's like a treasure hunt — each clue tells you where the next one is.",
    shortDescription: "A sequence of nodes where each node points to the next node in memory.",
    operations: ["Insert at Head", "Delete at Tail", "Search", "Traverse"],
    timeComplexity: { access: "O(n)", search: "O(n)", insert: "O(1) at head", delete: "O(n) at tail" },
    advantages: ["Dynamic size", "Efficient insertions/deletions", "No wasted memory"],
    disadvantages: ["No random access", "Extra memory for pointers", "Not cache friendly"],
    useCases: ["Implementation of stacks/queues", "Music playlists", "Undo functionality", "Memory management"],
  },
  {
    slug: "stack",
    name: "Stack",
    category: "Linear",
    difficulty: "Beginner",
    description:
      "A stack follows the Last In, First Out (LIFO) principle. The last element added is the first one removed. Think of a stack of plates — you always take the top plate and add new plates to the top.",
    shortDescription: "A LIFO (Last In, First Out) collection where elements are added and removed from the top.",
    operations: ["Push", "Pop", "Peek", "isEmpty"],
    timeComplexity: { access: "O(n)", search: "O(n)", insert: "O(1)", delete: "O(1)" },
    advantages: ["Simple implementation", "Memory efficient", "LIFO management"],
    disadvantages: ["No random access", "Limited capacity in some implementations", "Overflow risk"],
    useCases: ["Undo/Redo", "Function call stack", "Expression evaluation", "Browser back button"],
  },
  {
    slug: "queue",
    name: "Queue",
    category: "Linear",
    difficulty: "Beginner",
    description:
      "A queue follows the First In, First Out (FIFO) principle. The first element added is the first one removed. Think of a line at a store — the first person in line gets served first.",
    shortDescription: "A FIFO (First In, First Out) collection where elements are added at the back and removed from the front.",
    operations: ["Enqueue", "Dequeue", "Peek", "isEmpty"],
    timeComplexity: { access: "O(n)", search: "O(n)", insert: "O(1)", delete: "O(1)" },
    advantages: ["FIFO order maintained", "Simple implementation", "Fair scheduling"],
    disadvantages: ["No random access", "Limited in some implementations"],
    useCases: ["Print queue", "Task scheduling", "BFS traversal", "Buffering"],
  },
  {
    slug: "deque",
    name: "Deque",
    category: "Linear",
    difficulty: "Intermediate",
    description:
      "A deque (double-ended queue) allows insertion and removal from both ends. It's like a queue but more flexible — you can add or remove from either the front or the back.",
    shortDescription: "A double-ended queue that allows insertion and removal from both ends.",
    operations: ["Add Front", "Add Back", "Remove Front", "Remove Back", "Peek"],
    timeComplexity: { access: "O(n)", search: "O(n)", insert: "O(1)", delete: "O(1)" },
    advantages: ["Flexible insertion/removal", "Can function as stack or queue", "Efficient both ends"],
    disadvantages: ["More complex implementation", "No random access"],
    useCases: ["Sliding window problems", "Undo history", "Job scheduling", "Palindrome checking"],
  },
  {
    slug: "binary-tree",
    name: "Binary Tree",
    category: "Non-Linear",
    difficulty: "Intermediate",
    description:
      "A binary tree is a hierarchical data structure where each node has at most two children, called left and right. It's like a family tree — each person can have at most two direct children.",
    shortDescription: "A hierarchical tree where each node has at most two children.",
    operations: ["Insert", "Delete", "Search", "Traverse (In/Pre/Post Order)"],
    timeComplexity: { access: "O(n)", search: "O(n)", insert: "O(n)", delete: "O(n)" },
    advantages: ["Hierarchical data representation", "Efficient searching (in BST)", "Multiple traversal methods"],
    disadvantages: ["No built-in ordering", "Can become skewed", "Complex deletion"],
    useCases: ["File systems", "Organization charts", "Expression parsing", "Decision trees"],
  },
  {
    slug: "binary-search-tree",
    name: "Binary Search Tree",
    category: "Non-Linear",
    difficulty: "Intermediate",
    description:
      "A BST is a binary tree where the left child is smaller than the parent and the right child is larger. In a balanced tree, this ordering makes searching efficient because each comparison chooses one subtree; an unbalanced tree can degrade to linear time.",
    shortDescription: "A sorted binary tree where left children are smaller and right children are larger.",
    operations: ["Insert", "Delete", "Search", "Find Min/Max"],
    timeComplexity: { access: "O(log n) average, O(n) worst", search: "O(log n) average, O(n) worst", insert: "O(log n) average, O(n) worst", delete: "O(log n) average, O(n) worst" },
    advantages: ["Efficient search", "Ordered data", "Flexible size"],
    disadvantages: ["Can become unbalanced", "No guaranteed O(log n)", "Complex deletion"],
    useCases: ["Database indexing", "File system organization", "Expression trees", "Dictionary implementation"],
  },
  {
    slug: "heap",
    name: "Heap",
    category: "Non-Linear",
    difficulty: "Intermediate",
    description:
      "A heap is a complete binary tree where the parent is always larger (max-heap) or smaller (min-heap) than its children. Think of it like a pyramid where the most important element is always at the top.",
    shortDescription: "A complete binary tree where each parent is greater (max) or smaller (min) than its children.",
    operations: ["Insert", "Extract Max/Min", "Peek", "Heapify"],
    timeComplexity: { access: "O(1) for min/max", search: "O(n)", insert: "O(log n)", delete: "O(log n)" },
    advantages: ["Fast access to min/max", "Efficient priority queues", "Good for sorting"],
    disadvantages: ["Not sorted", "Slow search", "Complex implementation"],
    useCases: ["Priority queues", "Heap sort", "Finding Kth largest/smallest", "Median maintenance"],
  },
  {
    slug: "graph",
    name: "Graph",
    category: "Non-Linear",
    difficulty: "Advanced",
    description:
      "A graph is a collection of vertices (nodes) connected by edges (links). It can model relationships between any objects. Think of a social network — people are nodes and friendships are edges.",
    shortDescription: "A collection of vertices connected by edges, modeling relationships between objects.",
    operations: ["Add Vertex", "Add Edge", "Remove Vertex", "BFS", "DFS"],
    timeComplexity: { access: "O(1) for vertex", search: "O(V + E)", insert: "O(1)", delete: "O(V + E)" },
    advantages: ["Models complex relationships", "Flexible structure", "Many algorithms available"],
    disadvantages: ["Complex implementation", "Memory intensive", "Hard to visualize"],
    useCases: ["Social networks", "Maps/navigation", "Network routing", "Dependency resolution"],
  },
  {
    slug: "trie",
    name: "Trie",
    category: "Non-Linear",
    difficulty: "Advanced",
    description:
      "A trie is a tree-like data structure used to store strings. Each node represents a character, and paths from root to leaf represent complete words. It's like a dictionary where each letter leads you closer to the word.",
    shortDescription: "A tree for storing strings where each node represents a character.",
    operations: ["Insert", "Search", "Delete", "StartsWith"],
    timeComplexity: { access: "O(m) where m is key length", search: "O(m)", insert: "O(m)", delete: "O(m)" },
    advantages: ["Fast prefix search", "No collisions", "Alphabetical ordering"],
    disadvantages: ["Memory intensive", "Complex implementation", "Only for string-like keys"],
    useCases: ["Autocomplete", "Spell checkers", "Word games", "IP routing"],
  },
  {
    slug: "hash-table",
    name: "Hash Table",
    category: "Hash-Based",
    difficulty: "Intermediate",
    description:
      "A hash table maps keys to values using a hash function. It computes an index into an array of buckets, from which the desired value can be found. Think of it like a locker system — the hash function tells you exactly which locker to open.",
    shortDescription: "A key-value store that uses hashing for O(1) average access time.",
    operations: ["Insert", "Delete", "Search", "Resize"],
    timeComplexity: { access: "O(1) average", search: "O(1) average", insert: "O(1) average", delete: "O(1) average" },
    advantages: ["Fast average operations", "Flexible keys", "No ordering required"],
    disadvantages: ["Worst case O(n)", "Hash collisions", "No ordering", "Memory overhead"],
    useCases: ["Dictionaries", "Caching", "Database indexing", "Symbol tables"],
  },
];

export const algorithms: Algorithm[] = [
  {
    slug: "linear-search",
    name: "Linear Search",
    category: "Searching",
    difficulty: "Beginner",
    description:
      "Linear search checks each element one by one from the beginning until the target is found or the array ends. It's the simplest search algorithm — like reading every name in a phone book until you find the one you're looking for.",
    shortDescription: "Check each element sequentially until the target is found.",
    timeComplexity: { best: "O(1)", average: "O(n)", worst: "O(n)" },
    spaceComplexity: "O(1)",
    useCases: ["Small unsorted arrays", "Simple searches", "When data is not sorted"],
    steps: [
      { description: "Start at the first element", explanation: "We begin by looking at the very first element in the array.", codeLine: 0 },
      { description: "Compare current element with target", explanation: "Check if the current element matches the value we are searching for.", whyDidItDoThat: "We compare each element because linear search has no ordering to skip elements.", codeLine: 1 },
      { description: "If match found, return index", explanation: "We found the target! Return the current index.", codeLine: 2 },
      { description: "If no match, move to next element", explanation: "The current element is not our target. Move to the next one.", codeLine: 3 },
      { description: "If end reached, target not found", explanation: "We checked every element and did not find the target.", codeLine: 4 },
    ],
  },
  {
    slug: "binary-search",
    name: "Binary Search",
    category: "Searching",
    difficulty: "Intermediate",
    description:
      "Binary search works on sorted arrays by repeatedly dividing the search interval in half. Compare the target with the middle element — if it matches, done. If target is smaller, search the left half. If larger, search the right half.",
    shortDescription: "Efficiently find a target in a sorted array by repeatedly halving the search space.",
    timeComplexity: { best: "O(1)", average: "O(log n)", worst: "O(log n)" },
    spaceComplexity: "O(1)",
    useCases: ["Searching in sorted data", "Database indexing", "Dictionary lookup"],
    steps: [
      { description: "Set low to 0 and high to n-1", explanation: "Initialize our search boundaries to cover the entire array.", codeLine: 0 },
      { description: "Calculate mid = (low + high) / 2", explanation: "Find the middle index of the current search range.", whyDidItDoThat: "By checking the middle, we can eliminate half the remaining elements each step.", codeLine: 1 },
      { description: "Compare mid element with target", explanation: "Check if the middle element matches our target.", codeLine: 2 },
      { description: "If target is smaller, search left half (high = mid - 1)", explanation: "The target must be in the lower half. Move our upper boundary down.", codeLine: 3 },
      { description: "If target is larger, search right half (low = mid + 1)", explanation: "The target must be in the upper half. Move our lower boundary up.", codeLine: 4 },
      { description: "Repeat until found or boundaries cross", explanation: "Keep narrowing until we find the target or determine it's not there.", codeLine: 5 },
    ],
  },
  {
    slug: "bubble-sort",
    name: "Bubble Sort",
    category: "Sorting",
    difficulty: "Beginner",
    description:
      "Bubble sort repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order. The pass through the list is repeated until the list is sorted. Larger elements 'bubble up' to the end.",
    shortDescription: "Repeatedly compare adjacent elements and swap them if they're in the wrong order.",
    timeComplexity: { best: "O(n)", average: "O(n²)", worst: "O(n²)" },
    spaceComplexity: "O(1)",
    useCases: ["Educational purposes", "Small datasets", "Nearly sorted data"],
    steps: [
      { description: "Start from the beginning of the array", explanation: "We begin a new pass through the array from the first element.", codeLine: 0 },
      { description: "Compare adjacent elements", explanation: "Check if the current element is greater than the next element.", whyDidItDoThat: "We compare adjacent elements because bubble sort works by swapping neighbors to gradually move elements to their correct positions.", codeLine: 1 },
      { description: "Swap if they are in wrong order", explanation: "Since the current element is larger, swap it with the next element.", codeLine: 2 },
      { description: "Move to next pair and repeat", explanation: "Advance to the next pair of elements and compare them.", codeLine: 3 },
      { description: "After each pass, largest unsorted element is in its final position", explanation: "The largest element has bubbled up to its correct position at the end.", whyDidItDoThat: "Each pass guarantees at least one more element reaches its final sorted position.", codeLine: 4 },
      { description: "Repeat until no swaps occur", explanation: "If a complete pass has no swaps, the array is fully sorted.", codeLine: 5 },
    ],
  },
  {
    slug: "selection-sort",
    name: "Selection Sort",
    category: "Sorting",
    difficulty: "Beginner",
    description:
      "Selection sort divides the array into sorted and unsorted regions. It repeatedly finds the minimum element from the unsorted region and moves it to the end of the sorted region.",
    shortDescription: "Find the minimum element and place it at the beginning, repeatedly.",
    timeComplexity: { best: "O(n²)", average: "O(n²)", worst: "O(n²)" },
    spaceComplexity: "O(1)",
    useCases: ["Small datasets", "When memory writes are expensive", "Educational purposes"],
    steps: [
      { description: "Find the minimum element in unsorted region", explanation: "Scan the unsorted portion to find the smallest element.", whyDidItDoThat: "By finding the minimum, we know exactly which element should go next in the sorted region.", codeLine: 0 },
      { description: "Swap minimum with first unsorted element", explanation: "Move the found minimum to its correct position.", codeLine: 1 },
      { description: "Move boundary between sorted and unsorted regions", explanation: "The sorted region grows by one element.", codeLine: 2 },
      { description: "Repeat until entire array is sorted", explanation: "Continue finding minimums and placing them until all elements are sorted.", codeLine: 3 },
    ],
  },
  {
    slug: "insertion-sort",
    name: "Insertion Sort",
    category: "Sorting",
    difficulty: "Beginner",
    description:
      "Insertion sort builds the sorted array one element at a time by picking each element and inserting it into its correct position among the previously sorted elements. Like sorting playing cards in your hand.",
    shortDescription: "Build the sorted array one element at a time by inserting each into its correct position.",
    timeComplexity: { best: "O(n)", average: "O(n²)", worst: "O(n²)" },
    spaceComplexity: "O(1)",
    useCases: ["Small datasets", "Nearly sorted data", "Online sorting"],
    steps: [
      { description: "Start with the second element (index 1)", explanation: "The first element is trivially sorted. We begin inserting from the second element.", codeLine: 0 },
      { description: "Compare current element with sorted portion", explanation: "Check where the current element fits in the sorted portion.", whyDidItDoThat: "We need to find the correct position by comparing with already-sorted elements.", codeLine: 1 },
      { description: "Shift larger elements to the right", explanation: "Make room for the current element by shifting elements right.", codeLine: 2 },
      { description: "Insert current element at correct position", explanation: "Place the current element in its proper sorted position.", codeLine: 3 },
      { description: "Repeat for all remaining elements", explanation: "Continue inserting each remaining element into the sorted portion.", codeLine: 4 },
    ],
  },
  {
    slug: "merge-sort",
    name: "Merge Sort",
    category: "Sorting",
    difficulty: "Intermediate",
    description:
      "Merge sort is a divide-and-conquer algorithm. It divides the array in half, recursively sorts each half, then merges the sorted halves. It guarantees O(n log n) time regardless of input.",
    shortDescription: "Divide the array in half, sort each half, then merge them together.",
    timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" },
    spaceComplexity: "O(n)",
    useCases: ["Large datasets", "Linked lists", "External sorting", "When stable sort is needed"],
    steps: [
      { description: "Divide array into two halves", explanation: "Split the array at the middle into two equal (or nearly equal) halves.", whyDidItDoThat: "Dividing reduces the problem size, making it easier to sort smaller pieces.", codeLine: 0 },
      { description: "Recursively sort left half", explanation: "Apply merge sort to the left half until single elements remain.", codeLine: 1 },
      { description: "Recursively sort right half", explanation: "Apply merge sort to the right half.", codeLine: 2 },
      { description: "Merge the two sorted halves", explanation: "Combine the two sorted halves by comparing elements from each and placing the smaller one first.", codeLine: 3 },
      { description: "Continue merging up the recursion tree", explanation: "Merged results bubble up, creating larger sorted subarrays until the whole array is sorted.", codeLine: 4 },
    ],
  },
  {
    slug: "quick-sort",
    name: "Quick Sort",
    category: "Sorting",
    difficulty: "Intermediate",
    description:
      "Quick sort selects a 'pivot' element and partitions the array around it — elements smaller than the pivot go left, larger go right. Then recursively sorts the partitions. Very fast in practice.",
    shortDescription: "Pick a pivot, partition elements around it, then recursively sort the partitions.",
    timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n²)" },
    spaceComplexity: "O(log n) average, O(n) worst",
    useCases: ["General-purpose sorting", "In-memory sorting", "When average performance matters"],
    steps: [
      { description: "Choose a pivot element", explanation: "Select an element as the pivot (e.g., last element, first, median, or random).", whyDidItDoThat: "The pivot divides the array. A good pivot choice leads to balanced partitions.", codeLine: 0 },
      { description: "Partition: move smaller elements left of pivot", explanation: "Rearrange so elements smaller than pivot are on the left.", codeLine: 1 },
      { description: "Partition: move larger elements right of pivot", explanation: "Elements larger than pivot go to the right.", codeLine: 2 },
      { description: "Place pivot in its correct sorted position", explanation: "The pivot is now in its final position in the sorted array.", codeLine: 3 },
      { description: "Recursively sort left partition", explanation: "Apply quick sort to elements left of the pivot.", codeLine: 4 },
      { description: "Recursively sort right partition", explanation: "Apply quick sort to elements right of the pivot.", codeLine: 5 },
    ],
  },
  {
    slug: "heap-sort",
    name: "Heap Sort",
    category: "Sorting",
    difficulty: "Advanced",
    description:
      "Heap sort first builds a max-heap from the array, then repeatedly extracts the maximum element and places it at the end, reducing the heap size each time.",
    shortDescription: "Build a max-heap, then repeatedly extract the maximum to sort the array.",
    timeComplexity: { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" },
    spaceComplexity: "O(1)",
    useCases: ["When guaranteed O(n log n) is needed", "In-place sorting", "Priority queue based sorting"],
    steps: [
      { description: "Build a max-heap from the array", explanation: "Rearrange the array so it satisfies the max-heap property.", whyDidItDoThat: "A max-heap guarantees the largest element is at the root, making extraction efficient.", codeLine: 0 },
      { description: "Swap root (max) with last element", explanation: "Move the largest element to its final position at the end.", codeLine: 1 },
      { description: "Reduce heap size by one", explanation: "The last position is now sorted, so we exclude it from the heap.", codeLine: 2 },
      { description: "Heapify the root", explanation: "Restore the max-heap property for the remaining elements.", codeLine: 3 },
      { description: "Repeat until heap size is 1", explanation: "Continue extracting the max and heapifying until all elements are sorted.", codeLine: 4 },
    ],
  },
  {
    slug: "bfs",
    name: "Breadth-First Search (BFS)",
    category: "Graph",
    difficulty: "Intermediate",
    description:
      "BFS explores a graph level by level, visiting all neighbors of a node before moving to the next level. It uses a queue to track which nodes to visit next.",
    shortDescription: "Explore a graph level by level using a queue.",
    timeComplexity: { best: "O(V + E)", average: "O(V + E)", worst: "O(V + E)" },
    spaceComplexity: "O(V)",
    useCases: ["Shortest path (unweighted)", "Level-order traversal", "Finding connected components"],
    steps: [
      { description: "Start at the source node, enqueue it", explanation: "Mark the starting node as visited and add it to the queue.", codeLine: 0 },
      { description: "Dequeue a node and process it", explanation: "Remove the front node from the queue and visit it.", codeLine: 1 },
      { description: "Enqueue all unvisited neighbors", explanation: "Add all unvisited adjacent nodes to the queue.", whyDidItDoThat: "By processing neighbors before deeper nodes, we ensure level-by-level exploration.", codeLine: 2 },
      { description: "Mark neighbors as visited", explanation: "Prevent revisiting nodes to avoid infinite loops.", codeLine: 3 },
      { description: "Repeat until queue is empty", explanation: "Continue until all reachable nodes have been visited.", codeLine: 4 },
    ],
  },
  {
    slug: "dfs",
    name: "Depth-First Search (DFS)",
    category: "Graph",
    difficulty: "Intermediate",
    description:
      "DFS explores a graph by going as deep as possible along each branch before backtracking. It can be implemented using recursion or a stack.",
    shortDescription: "Explore as deep as possible along each branch before backtracking.",
    timeComplexity: { best: "O(V + E)", average: "O(V + E)", worst: "O(V + E)" },
    spaceComplexity: "O(V)",
    useCases: ["Cycle detection", "Topological sorting", "Path finding", "Maze solving"],
    steps: [
      { description: "Start at the source node, push onto stack", explanation: "Mark the starting node as visited and push it onto the stack.", codeLine: 0 },
      { description: "Pop a node from the stack", explanation: "Remove the top node from the stack and visit it.", codeLine: 1 },
      { description: "Push all unvisited neighbors onto stack", explanation: "Add unvisited adjacent nodes to the stack.", whyDidItDoThat: "Using a stack means we go deeper before going wider — last pushed is first visited.", codeLine: 2 },
      { description: "Mark neighbors as visited", explanation: "Prevent revisiting nodes.", codeLine: 3 },
      { description: "Repeat until stack is empty", explanation: "Continue until all reachable nodes have been visited.", codeLine: 4 },
    ],
  },
  {
    slug: "dijkstra",
    name: "Dijkstra's Algorithm",
    category: "Graph",
    difficulty: "Advanced",
    description:
      "Dijkstra's algorithm finds the shortest path from a source to all other vertices in a weighted graph with non-negative edge weights. It uses a priority queue to always process the closest unvisited node.",
    shortDescription: "Find shortest paths in a weighted graph using a priority queue.",
    timeComplexity: { best: "O((V + E) log V)", average: "O((V + E) log V)", worst: "O(V²)" },
    spaceComplexity: "O(V)",
    useCases: ["GPS navigation", "Network routing", "Robot path planning", "Game AI"],
    steps: [
      { description: "Set source distance to 0, all others to infinity", explanation: "Initialize: the source is 0 distance from itself, everything else is unknown.", codeLine: 0 },
      { description: "Add all nodes to priority queue", explanation: "Start with all nodes unvisited in the priority queue.", codeLine: 1 },
      { description: "Extract node with minimum distance", explanation: "Always process the closest unvisited node first.", whyDidItDoThat: "Greedy choice: the closest node cannot be improved by going through another unvisited node.", codeLine: 2 },
      { description: "Update distances of neighbors", explanation: "For each neighbor, check if going through the current node gives a shorter path.", codeLine: 3 },
      { description: "Mark current node as visited", explanation: "Once processed, the shortest distance to this node is final.", codeLine: 4 },
      { description: "Repeat until all nodes are visited", explanation: "Continue until we've found shortest paths to all reachable nodes.", codeLine: 5 },
    ],
  },
];

export const challenges: Challenge[] = [
  {
    id: "c1",
    question: "Which algorithm would be most efficient for finding a number in a sorted array?",
    options: ["Linear Search", "Binary Search", "Bubble Sort", "Selection Sort"],
    correctAnswer: 1,
    explanation: "Binary search is optimal for sorted arrays because it eliminates half the remaining elements with each comparison, giving O(log n) time complexity.",
    difficulty: "Easy",
    category: "Searching",
  },
  {
    id: "c2",
    question: "What does a Stack follow?",
    options: ["FIFO (First In, First Out)", "LIFO (Last In, First Out)", "Random Access", "Priority Order"],
    correctAnswer: 1,
    explanation: "A Stack follows LIFO — the last element pushed is the first one popped, like a stack of plates.",
    difficulty: "Easy",
    category: "Data Structures",
  },
  {
    id: "c3",
    question: "What is the worst-case time complexity of Quick Sort?",
    options: ["O(n log n)", "O(n²)", "O(n)", "O(log n)"],
    correctAnswer: 1,
    explanation: "Quick Sort's worst case is O(n²), which happens when the pivot selection consistently creates the most unbalanced partitions (e.g., already sorted array with first element as pivot).",
    difficulty: "Medium",
    category: "Sorting",
  },
  {
    id: "c4",
    question: "Which data structure is used by BFS to traverse a graph?",
    options: ["Stack", "Queue", "Heap", "Tree"],
    correctAnswer: 1,
    explanation: "BFS uses a Queue (FIFO) to explore nodes level by level, ensuring all nodes at distance d are visited before nodes at distance d+1.",
    difficulty: "Easy",
    category: "Graph Algorithms",
  },
  {
    id: "c5",
    question: "Which sorting algorithm is guaranteed O(n log n) in all cases?",
    options: ["Bubble Sort", "Quick Sort", "Merge Sort", "Insertion Sort"],
    correctAnswer: 2,
    explanation: "Merge Sort always divides the array in half and merges, giving guaranteed O(n log n) regardless of input. Quick Sort degrades to O(n²) in worst case.",
    difficulty: "Medium",
    category: "Sorting",
  },
  {
    id: "c6",
    question: "What is the time complexity of accessing an element in a Hash Table (average case)?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n²)"],
    correctAnswer: 0,
    explanation: "Hash Tables provide O(1) average case for access, insert, and delete because the hash function directly computes the index from the key.",
    difficulty: "Easy",
    category: "Hash-Based",
  },
  {
    id: "c7",
    question: "What is a key advantage of a Heap?",
    options: ["Fast search for any element", "O(1) access to minimum or maximum", "Sorted data at all times", "No memory overhead"],
    correctAnswer: 1,
    explanation: "A Heap provides O(1) access to the minimum (min-heap) or maximum (max-heap) element, making it ideal for priority queue implementations.",
    difficulty: "Medium",
    category: "Data Structures",
  },
  {
    id: "c8",
    question: "Which algorithm finds the shortest path in a weighted graph?",
    options: ["BFS", "DFS", "Dijkstra's Algorithm", "Merge Sort"],
    correctAnswer: 2,
    explanation: "Dijkstra's algorithm specifically finds shortest paths in weighted graphs with non-negative edge weights using a greedy approach with a priority queue.",
    difficulty: "Medium",
    category: "Graph Algorithms",
  },
  {
    id: "c9",
    question: "What is the space complexity of Merge Sort?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    correctAnswer: 2,
    explanation: "Merge Sort requires O(n) extra space because it needs temporary arrays to merge the sorted subarrays.",
    difficulty: "Hard",
    category: "Sorting",
  },
  {
    id: "c10",
    question: "In which data structure would you implement an undo/redo feature?",
    options: ["Queue", "Stack", "Heap", "Array"],
    correctAnswer: 1,
    explanation: "Stacks are perfect for undo/redo because of LIFO order — the most recent action is the first to be undone.",
    difficulty: "Easy",
    category: "Data Structures",
  },
];

export const allSearchableItems = [
  ...dataStructures.map((ds) => ({ type: "data-structure" as const, slug: ds.slug, name: ds.name, description: ds.shortDescription })),
  ...algorithms.map((a) => ({ type: "algorithm" as const, slug: a.slug, name: a.name, description: a.shortDescription })),
];
